name: MacOS

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install ninja

      - name: Configure
        shell: bash
        run: |
          cmake -B ${{github.workspace}}/build \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -G "Ninja" \
            -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl \
            -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib

      - name: Build
        shell: bash
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Run
        shell: bash
        run: |
          cd ${{github.workspace}}/build/src
          ./https_request https://example.com
